# Generated by Django 5.2.7 on 2025-10-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('property_type', models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда')], max_length=10, verbose_name='Тип оголошення')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('currency', models.CharField(choices=[('USD', '$'), ('UAH', '₴'), ('EUR', '€')], default='UAH', max_length=3, verbose_name='Валюта')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площа (м²)')),
                ('rooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість кімнат')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість спалень')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість ванних')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Поверх')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всього поверхів')),
                ('balcony', models.BooleanField(default=False, verbose_name='Балкон')),
                ('parking', models.BooleanField(default=False, verbose_name='Паркінг')),
                ('elevator', models.BooleanField(default=False, verbose_name='Ліфт')),
                ('furniture', models.CharField(choices=[('furnished', 'Мебльована'), ('partial', 'Частково'), ('empty', 'Без меблів'), ('unknown', 'Не вказано')], default='unknown', max_length=20, verbose_name='Меблі')),
                ('repair', models.CharField(blank=True, choices=[('none', 'Без ремонту'), ('cosmetic', 'Косметичний'), ('euro', 'Євроремонт'), ('designer', 'Дизайнерський')], max_length=20, null=True, verbose_name='Стан ремонту')),
                ('building_type', models.CharField(blank=True, choices=[('panel', 'Панельний'), ('brick', 'Цегляний'), ('new', 'Новобудова'), ('modern', 'Сучасний')], max_length=20, null=True, verbose_name='Тип будинку')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактна особа')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
            ],
            options={
                'verbose_name': 'Нерухомість',
                'verbose_name_plural': 'Нерухомість',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Нерухомість')),
            ],
            options={
                'verbose_name': 'Зображення нерухомості',
                'verbose_name_plural': 'Зображення нерухомості',
                'ordering': ['-is_main', 'order'],
            },
        ),
    ]
